// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// search_random_trails_in_linguistic_network
void search_random_trails_in_linguistic_network(const DataFrame& arcs_df, const unsigned long M, const unsigned long N, const bool is_all_ngrams_up_to_n, const unsigned long I, const bool use_boolean_instead_of_real_scoring, const std::string& GraphViz_file_path, const std::string& SRILM_counts_file_path);
RcppExport SEXP feat_search_random_trails_in_linguistic_network(SEXP arcs_dfSEXP, SEXP MSEXP, SEXP NSEXP, SEXP is_all_ngrams_up_to_nSEXP, SEXP ISEXP, SEXP use_boolean_instead_of_real_scoringSEXP, SEXP GraphViz_file_pathSEXP, SEXP SRILM_counts_file_pathSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const DataFrame& >::type arcs_df(arcs_dfSEXP);
    Rcpp::traits::input_parameter< const unsigned long >::type M(MSEXP);
    Rcpp::traits::input_parameter< const unsigned long >::type N(NSEXP);
    Rcpp::traits::input_parameter< const bool >::type is_all_ngrams_up_to_n(is_all_ngrams_up_to_nSEXP);
    Rcpp::traits::input_parameter< const unsigned long >::type I(ISEXP);
    Rcpp::traits::input_parameter< const bool >::type use_boolean_instead_of_real_scoring(use_boolean_instead_of_real_scoringSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type GraphViz_file_path(GraphViz_file_pathSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type SRILM_counts_file_path(SRILM_counts_file_pathSEXP);
    search_random_trails_in_linguistic_network(arcs_df, M, N, is_all_ngrams_up_to_n, I, use_boolean_instead_of_real_scoring, GraphViz_file_path, SRILM_counts_file_path);
    return R_NilValue;
END_RCPP
}
