# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

enumerate_random_trails_on_linguistic_network <- function(arcs_list_df, arcs_scores_dmat, n_strides_to_take, N, is_all_ngrams_up_to_n, n_iterations, GraphViz_file_path, SRILM_counts_file_path) {
    invisible(.Call('feat_enumerate_random_trails_on_linguistic_network', PACKAGE = 'feat', arcs_list_df, arcs_scores_dmat, n_strides_to_take, N, is_all_ngrams_up_to_n, n_iterations, GraphViz_file_path, SRILM_counts_file_path))
}

