# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

search_random_trails_in_linguistic_network <- function(arcs_df, M, N, is_all_ngrams_up_to_n, I, use_boolean_instead_of_real_scoring, GraphViz_file_path, SRILM_counts_file_path) {
    invisible(.Call('feat_search_random_trails_in_linguistic_network', PACKAGE = 'feat', arcs_df, M, N, is_all_ngrams_up_to_n, I, use_boolean_instead_of_real_scoring, GraphViz_file_path, SRILM_counts_file_path))
}

